# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: heartbeat

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    ports:
      - "9090:9090"
      - "9229:9229"
    volumes:
      - ./server/src:/server/src
      - ./server/nodemon.json:/server/nodemon.json

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    ports:
      - "8080:3000"