# docker-compose.yml
version: "3"
services:
  realtime:
    image: supabase/realtime
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_NAME: heartbeat
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      SECURE_CHANNELS: 'false'
    depends_on:
      - postgres

  postgres:
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/init:/docker-entrypoint-initdb.d/
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: heartbeat

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - realtime
    ports:
      - "9090:9090"
      - "9229:9229"
    volumes:
      - ./server/src:/server/src
      - ./server/nodemon.json:/server/nodemon.json

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    ports:
      - "8080:3000"
