# docker-compose.yml
version: "3"
services:
  realtime:
    image: supabase/realtime
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      PORT: 4000
      SECURE_CHANNELS: 'false'
    depends_on:
      - postgres

  postgres:
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
      # initial setup of tables etc.
      - ./server/db/init:/docker-entrypoint-initdb.d/
      # keep data between boots
      - ./postgres-data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - realtime
    ports:
      - "9090:9090"
      - "9229:9229"
    environment:
      - NODE_ENV
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  rest-api:
    build:
      context: ./
      dockerfile: ./rest-api/Dockerfile
    depends_on:
      - server
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV
